version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - APP_UNITS=metric
      - APP_LANG=pl
      - API_BASE_URL=https://api.openweathermap.org/data/2.5
      - API_KEY=${API_KEY}
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - API_KEY=${API_KEY}
    entrypoint: ["./server.test"]
    command: ["-test.v"]